### ISSUE TITLE
Create Postman Account dedicated to SIG-Travel

### ISSUE THREAD

**Issue by namdeirf** [OAI/sig-travel#41]
The SIG-Travel team has been leveraging Postman collections. There was a request to create a dedicated account to be the single source of truth for the SIG-Travel collection.

**Comment by swaldron58** [comment]
Created sigtrravelwg1 as a user name and gmail address. Invited myself and Luis to team. Will do more after I get some education.

**Comment by swaldron58** [comment]
done for now
